version: 2

sources:
  - name: raw_pos
    database: frostbyte_tasty_bytes
    schema: raw_pos
    tables:
      - name: country
      - name: franchise
      - name: location
      - name: menu
      - name: order_detail
      - name: order_header
      - name: truck
      
  - name: raw_customer
    database: frostbyte_tasty_bytes
    schema: raw_customer
    tables:
      - name: customer_loyalty

